### PR TITLE
Prepare for 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by azakus**

### CODE REVIEW

**Comment by stramel** [comment]
0.7.0 to 2.0.0?

**Comment by hyperpress** [comment]
Yes, I'm confused. Shouldn't that be 1

**Comment by Westbrook** [comment]
The `lit-element` repo on NPM accidentally burned the `1.0.0` release when it was owned by a non-Polymer individual. This will allow us to use `npm install lit-element` from now on...

**Comment by lacolaco** [comment]
I wonder this is good choice. Scoped package is the best for solving npm namespace problem. Also developers can know it is published by trustable organization. I want to know why polymer team chose old style.

**Comment by justinfagnani** [comment]
Scoped packages are great when you have a lot of related packages. This worked really well for the Polymer elements, because people had already begun taking the iron-* and paper-* names on npm before we could. And it saved us with Polymer core because likewise, someone else had the `polymer` package.

But I don't think `@polymer/polymer` was better than `polymer` for the core library. People (including myself) would accidentally run `npm i polymer`, and the import statements were unnecessarily long. I'm sure people have been accidentally running `npm i lit-element` too, and maybe being very confused because of it.

`npm i lit-element` and `import {LitElement} from 'lit-element';` are just simpler and easier to remember than their counterparts.

**Comment by stramel** [comment]
I agree with your points @justinfagnani.

Personally, I always forgot that `lit-element` was under the `@polymer` org. It would be cool/fun to do `@lit` org if you guys end up keeping the "lit" branding. `@lit/element` or `@lit/html`/`@lit/core`.

**Comment by justinfagnani** [comment]
We'd have to find out who this is: https://www.npmjs.com/~lit

**Comment by bennypowers** [comment]
```
$ npm info lit                                                                                                                                                                                                                                                               3257ms

lit@1.0.1 | MIT | deps: 3 | versions: 2
Micro-literate programming lib for javascript, inspired by docco

bin: litjs

dist
.tarball: https://registry.npmjs.org/lit/-/lit-1.0.1.tgz
.shasum: 9b65184e8f206b44703b9ca5b96b8dfd4ed75acc

dependencies:
ghm: 1.0.x          highlight.js: 7.0.x optimist: 0.3.x     

maintainers:
- caseman <casey.duncan@gmail.com>

dist-tags:
latest: 1.0.1  

published over a year ago by caseman <casey.duncan@gmail.com>
```

**Comment by bennypowers** [comment]
Also,

```
npx npm-user-cli lit                                                                                                                                                                                                                                                    13.4s
npx: installed 109 in 8.333s
Email: super122425069@126.com
```

**Comment by bennypowers** [comment]
Anecdotally, sometimes NPM will reassign a name if you ask them nicely and have a more widely used library.

**Pull request merged**
