### PR TITLE
amd

### LINKED ISSUE #140: Provide bundled JavaScript files.
### Description

The browser does not support the bare import.
It is impossible to use lit-element without toolchain (webpack or rollup) now
as lit-element use bare import.
https://github.com/Polymer/lit-element/blob/2433ce376521aa8ab5272aa9c12a49ee74ac8c4e/src/lit-element.ts#L14-L23
or the browser will throw the error:

```err
TypeError: Module specifier does not start with "/", "./", or "../".
```
---
It is better to provide different versions of bundled files. Such as UMD, CommonJS and ES Module.
There is an [example](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds) in Vue project.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v0.5.2
- webcomponents: v2.0.2

### PR DESCRIPTION
**Pull request by taoqf**
### Reference Issue

Fixes #140

### CODE REVIEW

**Comment by taoqf** [comment]
https://github.com/Polymer/lit-html/pulls

**Comment by taoqf** [comment]
https://github.com/Polymer/lit-html/pull/1019

**Comment by taoqf** [comment]
@googlebot I could not signed it as a chinese developer!

**Comment by taoqf** [comment]
@justinfagnani Would you pls take a look at this?

**Comment by justinfagnani** [comment]
Hi @taoqf and thanks for the PR. To be clear, we're not interested in foxing #140 as phrased. #603  is about providing a pre-built file basically for demo consumption only.

We'd still want to distribute modules, since all current browsers support them and do not support AMD without a loader. And I really would want the files to be named appropriately scary so that developers don't use them in production, like `lit-element/prebuilt/lit-element-not-for-production.js`, and include a `console.warn()` to not use them either. The goal of #603 is also to indicate a more realistic file-size, so we'd want to run the bundle through a minifier too.

I think Rollup would be the best tool for this, rather than an alternate tsconfig file.

**Comment by taoqf** [comment]
<https://www.npmjs.com/package/@taoqf/lit-element>
<https://www.npmjs.com/package/@taoqf/lit-html>
will do for now.

**Pull request closed without merging**
