### PR TITLE
Add Closure lint

### LINKED ISSUE #80: Closure compiler chokes on LitElement
When I try to use Closure Compiler on code that uses `LitElement`, I get the error `The class in an extends clause must be a qualified name`. It looks like this is a known issue for Closure: https://github.com/google/closure-compiler/issues/2650 but unclear if/when they are planning to address it.

### PR DESCRIPTION
**Pull request by TimvdLippe**
Enable Closure linter to make sure Closure Compiler can work just fine on `lit-element`. I was unable to reproduce the issues @joncass was encountering.

Related to #80

### CODE REVIEW

**Comment by joncass** [comment]
Thanks for working on this @TimvdLippe. I was unable to get `npm run lint` to execute on the `closure-lint` branch. I get:
```
/dev/playground/lit-element$ npm run lint

> @polymer/lit-element@0.5.1 lint /dev/playground/lit-element
> tslint --project ./ && gulp closure

No valid rules have been specified for TypeScript files
[07:53:53] Using gulpfile ~/dev/playground/lit-element/gulpfile.js
[07:53:53] Starting 'closure'...
[07:53:53] 'closure' errored after 11 ms
[07:53:53] Error: File not found with singular glob: /dev/playground/lit-element/lit-element.js
    at Glob.<anonymous> (/dev/playground/lit-element/node_modules/glob-stream/index.js:41:11)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/dev/playground/lit-element/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/dev/playground/lit-element/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/dev/playground/lit-element/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /dev/playground/lit-element/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/dev/playground/lit-element/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/dev/playground/lit-element/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
```

Thoughts on what I might be doing wrong?

**Comment by TimvdLippe** [comment]
You first have to build the project. E.g. `npm run build`

**Comment by joncass** [comment]
Got it, thanks. After running `npm run build` I can run `npm run lint` and it executes successfully.

However, when I change the `language_out` in the gulpfile to `ES5` (which is what I'm using in my project) then I can see the error from #80

**Comment by TimvdLippe** [comment]
Ah okay interesting. Will take a look 👍

**Comment by TimvdLippe** [comment]
@joncass Per https://github.com/google/closure-compiler/issues/1876#issuecomment-231138616 this appears to be a known limitation of the closure compiler. I am not sure what our options are in that case :cry:

**Comment by TimvdLippe** [comment]
I am no longer pursuing this PR.

**Pull request closed without merging**
